### ISSUE TITLE
카드 함수 구현

### ISSUE THREAD

**Issue by jujoko** [PADOTAGY/Halligali#19]
## 🌊 Issue

카드 구조체
Card : 카드 한 장 (카드 Id, 다음 카드 주소)
CardSet : 카드 뭉치 (맨 위 카드 주소, 카드 개수)

카드 리스트 생성 (readyGameboard) 
게임 시작 시 user와 npc의 카드 리스트를 생성

카드 드로우 (drawCard)
놓을 자리를 선택하면, 그 자리의 카드셋에 카드를 추가

이긴 사람이 카드 가져오기 (ringBell)
이긴 사람이 드로우된 카드를 모두 가져감.

## 📌 To-do

- [ ] 카드 구조체
- [ ] 카드 리스트 생성 
- [ ] 카드 드로우
- [ ] 이긴 사람이 카드 가져오기

**Comment by jujoko** [comment]
- [ ] 카드 구조체
- [ ] 카드 리스트 생성 
- [ ] 카드 드로우
- [ ] 이긴 사람이 카드 가져오기

**Comment by jujoko** [comment]
필요없어져서 닫아볼게요
