### ISSUE TITLE
[Feat] ringBell 함수 구현

### ISSUE THREAD

**Issue by jujoko** [PADOTAGY/Halligali#39]
## 🌊 Issue

user나 npc가 종을 치면, 낸 모든 카드를 이긴 사람의 카드세트에 합병합니다.
이때, 낸 모든 카드는 일부 섞입니다. (완벽히 랜덤으로 섞이지 않습니다.)

만약, 종을 잘못 쳤을 경우 패널티로 상대방에게 카드 한 장을 줍니다.

## 📌 To-do

- [x] ringBell 함수 구현
- [x] mergeSet 함수 구현
- [x] penalty 함수 구현
