### ISSUE TITLE
[Feat] 아이템 피드백 반영

### ISSUE THREAD

**Issue by annapo99** [PADOTAGY/Halligali#75]
## 📌 To-do

- [x] 폭탄 바로 사용
- [x] 아이템 설명 추가
- [x] 윈 아이템 글자 수정
- [x] 퀘스트 색 바뀌는 거 수정
- [ ] 아이템 퀘스트 조건 변경
